Repository angelolab/ark-analysis, pull requests merged in 2022-06, with the labels that each got.

#594 Added documentation for setting up development on M1
  docs/_rtd/development.md
Labels: documentation

#598 Added Release Drafter
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: enhancement

#603 Singleton list of dtype fix
  ark/utils/misc_utils.py
  ark/utils/misc_utils_test.py
Labels: bug

#601 Change default zip size
  ark/utils/deepcell_service_utils.py
Labels: bug

#607 Allow segmentation pipeline to handle blank images
  ark/segmentation/marker_quantification.py
  ark/segmentation/marker_quantification_test.py
Labels: bug

#592 Upgraded to Python 3.7
  .readthedocs.yml
  .travis.yml
  Dockerfile
  ark/segmentation/marker_quantification.py
  ark/utils/misc_utils.py
  docs/_rtd/development.md
  docs/conf.py
  requirements-test.txt
  requirements.txt
  setup.py
  start_docker.sh
Labels: dependencies

#617 VERSION 0.3.00 -> 0.3.1
  setup.py
Labels: bug

#624 PKG_FOLDER variable in `setup.py` cannot find `requirements.txt` due to filepath issue.
  setup.py
Labels: bug
