Repository angelolab/ark-analysis, pull requests merged in 2022-08, with the labels that each got.

#641 Create Mantis Project Function
  README.md
  ark/utils/notebooks_test.py
  ark/utils/notebooks_test_utils.py
  ark/utils/plot_utils.py
  ark/utils/plot_utils_test.py
  ark/utils/tiff_utils_test.py
  templates_ark/example_cell_clustering.ipynb
  templates_ark/example_pixel_clustering.ipynb
Labels: enhancement

#643 Added Batching Functionality to Pixel Mask Generation and FOV Saving
  ark/utils/data_utils.py
  ark/utils/data_utils_test.py
  ark/utils/load_utils.py
  ark/utils/notebooks_test_utils.py
  templates_ark/example_cell_clustering.ipynb
  templates_ark/example_pixel_clustering.ipynb
Labels: enhancement

#636 Docker Tags in line with ark-analysis Version
  .travis.yml
  Dockerfile
Labels: bug, enhancement

#648 Notebook Reorganization
  README.md
  ark/utils/notebooks_test.py
  templates_ark/1_Segment_Image_Data.ipynb
  templates_ark/2_Cluster_Pixels.ipynb
  templates_ark/3_Cluster_Cells.ipynb
  templates_ark/example_pairwise_spatial_enrichment.ipynb
Labels: documentation

#667 Mantis Project - Improved Filtering of user Supplied FOVs
  ark/utils/plot_utils.py
  ark/utils/plot_utils_test.py
  requirements.txt
Labels: bug

#650 Python 3.8 and Native Apple Silicon Support
  .gitignore
  .readthedocs.yml
  .travis.yml
  Dockerfile
  ark/analysis/dimensionality_reduction.py
  ark/phenotyping/cell_cluster_utils_test.py
  ark/phenotyping/pixel_cluster_utils_test.py
  ark/segmentation/regionprops_extraction.py
  ark/segmentation/regionprops_extraction_test.py
  ark/utils/deepcell_service_utils.py
  ark/utils/plot_utils_test.py
  ark/utils/synthetic_spatial_datagen.py
  ark/utils/tiff_utils.py
  docs/_rtd/development.md
  docs/conf.py
  docs/rtd-requirements.txt
  requirements-test.txt
  requirements.txt
  setup.py
Labels: documentation, dependencies

#660 Ark Pipeline Flowchart
  README.md
  docs/_images/ark_processing.png
  docs/_images/docker_preferences.png
  docs/_images/mantis_feature_file.png
  docs/_images/mantis_feature_view.png
  docs/_images/mantis_loading.png
Labels: documentation

#674 Next Release - v0.4.1
  docs/_rtd/development.md
  setup.py
  start_docker.sh
Labels: dependencies

#684 Fixed FlowSOM on Docker Image
  Dockerfile
Labels: dependencies
