Repository angelolab/ark-analysis, pull requests merged in 2022-11, with the labels that each got.

#802 Adjust load tiled imgs for toffy use
  ark/utils/data_utils.py
  ark/utils/load_utils.py
  ark/utils/load_utils_test.py
Labels: enhancement

#804 Next Release - v0.4.4
  setup.py
  start_docker.sh
Labels: dependencies

#808 Cell Table Assumptions
  README.md
  docs/_rtd/data_types.md
Labels: documentation

#805 Travis patchelf pypi_deploy Updates
  .travis.yml
  Dockerfile
  docs/_rtd/development.md
  requirements.txt
Labels: bug

#828 Added Parameter for Seg Mask Suffix for Mantis
  ark/phenotyping/post_cluster_utils.py
  ark/phenotyping/post_cluster_utils_test.py
  ark/utils/plot_utils.py
  ark/utils/plot_utils_test.py
Labels: enhancement

#838 Removed duplicate mantis fov loading
  ark/phenotyping/post_cluster_utils.py
Labels: bug

#840 Tagged Installation Instructions
  README.md
  docs/_rtd/development.md
Labels: documentation
