Repository angelolab/ark-analysis, pull requests merged in 2022-10, with the labels that each got.

#721 Next Release v0.4.2
  Dockerfile
  README.md
  docs/Makefile
  docs/_rtd/contributing.md
  docs/_rtd/development.md
  docs/_rtd/faq.md
  requirements.txt
  setup.py
  start_docker.sh
Labels: dependencies

#741 Settings name update
  ark/analysis/spatial_analysis.py
  ark/analysis/spatial_analysis_test.py
  ark/analysis/visualize_test.py
  ark/settings.py
  ark/spLDA/processing.py
  ark/spLDA/processing_test.py
  ark/utils/data_utils_test.py
  ark/utils/spatial_analysis_utils.py
  ark/utils/spatial_analysis_utils_test.py
  ark/utils/spatial_lda_utils.py
  ark/utils/spatial_lda_utils_test.py
  ark/utils/test_utils.py
  data/example_dataset/spatial_enrichment_input_data/example_expression_matrix.csv
  data/example_dataset/spatial_lda_input_data/example_cell_table.csv
  templates/LDA_Preprocessing.ipynb
  templates/LDA_Training_and_Inference.ipynb
  templates/example_pairwise_spatial_enrichment.ipynb
Labels: bug

#762 Optimize dataframe merging
  ark/segmentation/marker_quantification.py
  ark/utils/spatial_analysis_utils.py
Labels: enhancement

#772 Remove mibitiff option in notebooks
  templates/1_Segment_Image_Data.ipynb
  templates/2_Cluster_Pixels.ipynb
Labels: enhancement

#702 Image tiling script
  ark/utils/data_utils.py
  ark/utils/data_utils_test.py
  ark/utils/load_utils.py
  ark/utils/load_utils_test.py
  ark/utils/test_utils.py
  templates/Image_Stitching.ipynb
Labels: enhancement

#763 Example Dataset - Notebook 4
  .gitignore
  ark/segmentation/fiber_segmentation_test.py
  ark/utils/example_dataset.py
  ark/utils/example_dataset_test.py
  templates/4_Post_Clustering.ipynb
Labels: enhancement

#782 Notebook Update Tests with string args
  .travis.yml
  ark/utils/notebook_update_test.py
Labels: enhancement

#794 Local Caching
  ark/utils/example_dataset.py
  ark/utils/example_dataset_test.py
  templates/1_Segment_Image_Data.ipynb
  templates/2_Cluster_Pixels.ipynb
  templates/3_Cluster_Cells.ipynb
  templates/4_Post_Clustering.ipynb
Labels: enhancement

#796 Increase validate paths usage
  ark/phenotyping/cell_cluster_utils.py
  ark/phenotyping/pixel_cluster_utils.py
  ark/segmentation/fiber_segmentation_test.py
  ark/utils/data_utils.py
  ark/utils/data_utils_test.py
  ark/utils/io_utils.py
  ark/utils/io_utils_test.py
  ark/utils/load_utils_test.py
  ark/utils/metacluster_remap_gui/colormap_helper.py
  ark/utils/metacluster_remap_gui/file_reader.py
  ark/utils/misc_utils.py
  ark/utils/plot_utils.py
  ark/utils/spatial_analysis_utils_test.py
  ark/utils/spatial_lda_utils.py
  ark/utils/spatial_lda_utils_test.py
  ark/utils/test_utils.py
Labels: enhancement
